routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

    Route::get('/profile', [
        'uses' => 'ProfileController@index',
        'as' => 'profile',
    ]);

    Route::get('/profile-update-pass', [
        'uses' => 'ProfileController@pup',
        'as' => 'profile-update-pass',
    ]);

    Route::get('/profile-update', [
        'uses' => 'ProfileController@pu',
        'as' => 'profile-update',
    ]);

    Route::post('/profile-update-pass', [
        'uses' => 'ProfileController@pupx',
        'as' => 'profile-update-pass',
    ]);

    Route::post('/profile-update', [
        'uses' => 'ProfileController@pux',
        'as' => 'profile-update',
    ]);

    Route::group(['middleware' => ['role:Student']], function () {

        Route::get('/form-company', [
            'uses' => 'HomeController@company',
            'as' => 'requirements.company',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/timesheet-report', [
            'uses' => 'HomeController@reportTimesheet',
            'as' => 'report.timesheet',
        ]);

        Route::get('/form-information', [
            'uses' => 'HomeController@information',
            'as' => 'requirements.information',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/form-documents', [
            'uses' => 'HomeController@documents',
            'as' => 'requirements.documents',
            'middleware' => 'student.is-verified',
        ]);

        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);
        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);

    });

    Route::group(['middleware' => ['role:Company']], function () {

        Route::get('/company-students', [
            'uses' => 'DashboardController@companyStudents',
            'as' => 'company-students',
        ]);

        Route::get('/company-timesheets', [
            'uses' => 'DashboardController@timesheets',
            'as' => 'company-timesheets',
        ]);

        Route::get('/student-timesheet/{id}', [
            'uses' => 'DashboardController@studentTimesheet',
            'as' => 'student-timesheet',
        ]);

        Route::patch('/update-student-timesheet/{id}', [
            'uses' => 'DashboardController@updateStudentTimesheet',
            'as' => 'student-timesheet.update',
        ]);

    });

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);
});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Student', 'requirements']], function () {

    Route::resource('timesheet', 'TimesheetController');

    Route::post('/manual-add-time', [
        'uses' => 'TimesheetController@manualAddTime',
        'as' => 'manual.add.time',
    ]);

    Route::get('/ojt-form', [
        'uses' => 'ProfileController@ojtForm',
        'as' => 'ojt.form',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::resource('section', 'SectionController');

    Route::resource('company', 'CompanyController');

    Route::resource('requirement', 'RequirementController');

    Route::resource('post', 'PostController');

    Route::resource('user', 'UserController');

    Route::resource('student', 'StudentController');

    Route::get('/profile-check/{id}', [
        'uses' => 'ProfileController@profilecheck',
        'as' => 'profile.check',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('user', 'UserController');

    Route::post('/student/import', [
        'uses' => 'StudentController@importCsv',
        'as' => 'student.import',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'section', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::post('/revoke-req', [
        'uses' => 'HomeController@revokeReq',
        'as' => 'revoke.req',
    ]);

    Route::post('/verify-req', [
        'uses' => 'HomeController@verifyStudent',
        'as' => 'verifystudent',
    ]);
    Route::get('/{section}/students', [
        'uses' => 'SectionController@students',
        'as' => 'section.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'SectionController@studentDetach',
        'as' => 'section.student-detach',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'company', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::get('/{company}/students', [
        'uses' => 'CompanyController@students',
        'as' => 'company.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'CompanyController@studentDetach',
        'as' => 'company.student-detach',
    ]);

});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'student_number',
        'user_id',
        'company_id',
        'section_id',
        'address',
        'sex',
        'birthdate',
        'guardian_name',
        'guardian_contact',
        'remaining_time',
    ];

    public function requirements()
    {
        return $this->belongsToMany('App\Requirement')->withPivot('attachment')->withTimestamps();
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Role;
use App\Section;
use App\Student;
use App\User;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function index()
    {
        $students = Student::all();
        // $sections = Section::all();
        // $companies = Company::all();
        return view('student.index', compact('students'));
    }

    public function create()
    {
        $sections = Section::all();
        $companies = Company::all();
        return view('student.create', compact('sections', 'companies'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'student_number' => '|required|unique|max:250|regex:/^\d{2}-\d{4}-\d{3}$/',
            'first_name' => 'required|max:191',
            'last_name' => 'required|max:191',
            'middle_name' => 'max:191',
        ]);

        $code = 'oims-' . mt_rand(5, 99999);
        $role_student = Role::where('name', 'Student')->first();
        $user = new User;
        $user_data = [
            'student_number' => $request->student_number,
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'middle_name' => $request->middle_name,
            'username' => $code,
            'password' => bcrypt($code),
        ];
        $user->fill($user_data)->save();
        $user->roles()->attach($role_student);
        $student = new Student;
        $request->request->add(['user_id' => $user->id]);
        $student->fill($request->all())->save();
        return redirect()->route('student.index');
    }

    public function show($id)
    {
        return;
    }

    public function edit($id)
    {
        $student = Student::find($id);
        $sections = Section::all();
        $companies = Company::all();
        return view('student.edit', compact('student', 'sections', 'companies'));
    }

    public function update(Request $request, $id)
    {
        $student = Student::find($id);

        $this->validate($request, [
            'student_number' => '|required|max:250|regex:/^\d{2}-\d{4}-\d{3}$/|unique:students,student_number,' . $student->student_number,
            'first_name' => 'required|max:191',
            'last_name' => 'required|max:191',
            'middle_name' => 'max:191',
        ]);

        $student->user->update($request->all());
        $student->update($request->all());
        return redirect()->route('student.index');
    }

    public function destroy($id)
    {
        $student = Student::find($id);
        if (!empty($student->user)) {
            $student->user->delete();
        }
        $student->delete();
        return redirect()->back();
    }

    public function importCsv(Request $request)
    {

        if ($request->hasFile('csvs')) {
            $filesource = $request->file('csvs');
            $fileExtension = $filesource->getClientOriginalExtension();
            if ($fileExtension === 'csv') {
                $path = $request->file('csvs')->getRealPath();
                $data = \Excel::load($path)->get();
                $role_student = Role::where('name', 'Student')->first();
                if ($data->count()) {

                    foreach ($data as $key => $value) {

                        $check_regex_student_number = preg_match('/^\d{2}-\d{4}-\d{3}$/D', $value->student_number);

                        if ($check_regex_student_number === 1) {
                            $checker = Student::where('student_number', $value->student_number)->first();
                            if (empty($checker)) {
                                $code = 'oims-' . mt_rand(5, 99999);
                                $user_data = [
                                    'first_name' => $value->first_name,
                                    'last_name' => $value->last_name,
                                    'middle_name' => $value->middle_name,
                                    'username' => $code,
                                    'password' => bcrypt($code),
                                ];
                                $user = new User;
                                $user->fill($user_data)->save();
                                $user->roles()->attach($role_student);
                                $section = Section::where('name', $value->section)->where('school_year', $value->school_year)->first();
                                $student = new Student;
                                $student_data = [
                                    'user_id' => $user->id,
                                    'student_number' => (string) $value->student_number,
                                    'section_id' => !empty($section) ? $section->id : null,
                                ];
                                $student->fill($student_data)->save();
                            }
                        } else {
                            return redirect()->back()->withErrors('Wrong format student number');
                        }

                    }
                    return redirect()->back();
                }
            } else {
                return redirect()->back()->withErrors('It must be in CSV format');
            }
        }
        return redirect()->back();
    }
}

resources/views/student/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
              <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Create Student</span>
            </h3>
            </center>
            <hr>
            @include('includes._message')
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <form onsubmit="return confirm('Do you want to save this data?');" method="POST" action="{{ route('student.store') }}">
                        {{ csrf_field() }}
                              <div class="form-group">
                            <label for="student_number">Student Number (format 00-0000-000)</label>
                            <input id="student_number" type="text" class="form-control" name="student_number" value="{{ old('student_number') }}" required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" class="form-control" name="first_name" value="{{ old('first_name') }}" required>
                        </div>
                        <div class="form-group">
                            <label for="middle_name">Middle Name</label>
                            <input id="middle_name" type="text" class="form-control" name="middle_name" value="{{ old('middle_name') }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text" class="form-control" name="last_name" value="{{ old('last_name') }}" required>
                        </div>
                        <div class="form-group">
                            <label for="section_id">Section</label>
                            <select class="form-control" name="section_id" id="section_id" required>
                                <option {{ old('section_id') == null ? 'selected' : '' }} disabled>Select Section</option>
                                @foreach($sections as $section)
                                <option {{ old('section_id') == $section->id ? 'selected' : '' }} value="{{$section->id}}">{{$section->name}} ({{$section->school_year}})</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="company_id">Company</label>
                            <select class="form-control" name="company_id" id="company_id">
                                <option {{ old('company_id') == null ? 'selected' : '' }} value="">Select Company</option>
                                @foreach($companies as $company)
                                <option {{ old('company_id') == $company->id ? 'selected' : '' }} value="{{$company->id}}">{{$company->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
              <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Edit Student</span>
            </h3>
            </center>
            <hr>
            @include('includes._message')
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <form onsubmit="return confirm('Do you want to update this data?');" method="POST" action="{{ route('student.update', $student->id) }}">
                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}
                            <div class="form-group">
                            <label for="student_number">Student Number (format 00-0000-000)</label>
                            <input id="student_number" type="text" class="form-control" name="student_number" value="{{ $student->student_number }}" required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" class="form-control" name="first_name" value="{{ $student->user->first_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="middle_name">Middle Name</label>
                            <input id="middle_name" type="text" class="form-control" name="middle_name" value="{{ $student->user->middle_name }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text" class="form-control" name="last_name" value="{{ $student->user->last_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="section_id">Section</label>
                            <select class="form-control" name="section_id" id="section_id" required>
                                <option {{ $student->section_id == null ? 'selected' : '' }} disabled>Select Section</option>
                                @foreach($sections as $section)
                                <option {{ $student->section_id == $section->id ? 'selected' : '' }} value="{{$section->id}}">{{$section->name}} ({{$section->school_year}})</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Manage Student</span>
            </h3>
            </center>
            <hr>
    @include('includes._message')

            <br/>
            <div class="form-group">
                <strong><h3>Import Student Format: *CSV</h3><strong></strong>
                <p>Fields:</p>
                <ul>
                    <li>student_number (format 00-0000-000)</li>
                    <li>last_name</li>
                    <li>first_name</li>
                    <li>middle_name</li>
                    <li>section</li>
                    <li>school_year</li>
                </ul>

                <form id="import" action="{{route('student.import')}}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <button type="button" class="btn btn-info btn-lg" id="file-upload">
                        Import Student
                    </button>
                    <input onchange="this.form.submit()" type="file" name="csvs" accept=".csv" id="csv" style="visibility: hidden;">
                </form>
                <hr>
{{--                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createpost">
                    Create Student
                    </button>
 --}}
                    <a href="{{ route('student.create')}}" class="btn btn-primary">Create Student</a>

            </div>
            <hr>
            <div class="panel panel-default">
                <div class="panel-heading">Student list</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>Student Number</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Section</th>
                                    <th>Company</th>
                                    <th>Email Address</th>
                                    <th>Contact</th>
                                    <th>Is Verified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($students as $student)

                                <tr>
                                    <td>{{ $student->student_number }}</td>
                                    <td>
                                        <a href="{{route('profile.check', $student->user->id)}}">
                                        {{ $student->user->last_name }} {{ $student->user->first_name }} {{ $student->user->middle_name }}
                                        <a/>
                                    </td>
                                    <td>{{ $student->user->username }}</td>
                                    <td>{{ !empty($student->section) ? $student->section->name. ' | '. $student->section->school_year : '' }}</td>
                                    <td>{{ !empty($student->company) ? $student->company->name : '' }}</td>
                                    <td>{{ $student->user->email }}</td>
                                    <td>{{ $student->user->contact }}</td>
                                    <td>{{ $student->user->is_verified == 1 ? 'true' : 'false' }}</td>
                                    <td>
                                        <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#xxx-{{$student->id}}">Files</a>

                                    {{--       <button type="button" class="btn btn-info" data-toggle="modal" data-target="#editpost-{{$student->id}}">
                                            Edit
                                            </button> --}}

                                            <a class="btn btn-info" href="{{route('student.edit', $student->id)}}">Edit</a>


                                        <button type="submit" form="student-delete-{{$student->id}}" class="btn btn-danger">Delete</button>
                                        <form onsubmit="return confirm('Do you want to delete this data?');" id="student-delete-{{$student->id}}" action="{{route('student.destroy', $student->id)}}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                        </form>
                                    </td>
                                </tr>
                                @include('student.includes._tinay')
                                {{-- @include('student.includes._modalEdit') --}}

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- @include('student.includes._modalAdd') --}}
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();

        $("#file-upload").on('click',function(){
           $("#csv").click();
        });
    });
</script>
@endsection