routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

    Route::get('/profile', [
        'uses' => 'ProfileController@index',
        'as' => 'profile',
    ]);

    Route::get('/profile-update-pass', [
        'uses' => 'ProfileController@pup',
        'as' => 'profile-update-pass',
    ]);

    Route::get('/profile-update', [
        'uses' => 'ProfileController@pu',
        'as' => 'profile-update',
    ]);

    Route::post('/profile-update-pass', [
        'uses' => 'ProfileController@pupx',
        'as' => 'profile-update-pass',
    ]);

    Route::post('/profile-update', [
        'uses' => 'ProfileController@pux',
        'as' => 'profile-update',
    ]);

    Route::group(['middleware' => ['role:Student']], function () {

        Route::get('/form-company', [
            'uses' => 'HomeController@company',
            'as' => 'requirements.company',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/timesheet-report', [
            'uses' => 'HomeController@reportTimesheet',
            'as' => 'report.timesheet',
        ]);

        Route::get('/form-information', [
            'uses' => 'HomeController@information',
            'as' => 'requirements.information',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/form-documents', [
            'uses' => 'HomeController@documents',
            'as' => 'requirements.documents',
            'middleware' => 'student.is-verified',
        ]);

        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);
        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);

    });

    Route::group(['middleware' => ['role:Company']], function () {

        Route::get('/company-students', [
            'uses' => 'DashboardController@companyStudents',
            'as' => 'company-students',
        ]);

        Route::get('/company-timesheets', [
            'uses' => 'DashboardController@timesheets',
            'as' => 'company-timesheets',
        ]);

        Route::get('/student-timesheet/{id}', [
            'uses' => 'DashboardController@studentTimesheet',
            'as' => 'student-timesheet',
        ]);

        Route::patch('/update-student-timesheet/{id}', [
            'uses' => 'DashboardController@updateStudentTimesheet',
            'as' => 'student-timesheet.update',
        ]);

    });

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);
});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Student', 'requirements']], function () {

    Route::resource('timesheet', 'TimesheetController');

    Route::post('/manual-add-time', [
        'uses' => 'TimesheetController@manualAddTime',
        'as' => 'manual.add.time',
    ]);

    Route::get('/ojt-form', [
        'uses' => 'ProfileController@ojtForm',
        'as' => 'ojt.form',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::resource('section', 'SectionController');

    Route::resource('company', 'CompanyController');

    Route::resource('requirement', 'RequirementController');

    Route::resource('post', 'PostController');

    Route::resource('user', 'UserController');

    Route::resource('student', 'StudentController');

    Route::get('/profile-check/{id}', [
        'uses' => 'ProfileController@profilecheck',
        'as' => 'profile.check',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('user', 'UserController');

    Route::post('/student/import', [
        'uses' => 'StudentController@importCsv',
        'as' => 'student.import',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'section', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::post('/revoke-req', [
        'uses' => 'HomeController@revokeReq',
        'as' => 'revoke.req',
    ]);

    Route::post('/verify-req', [
        'uses' => 'HomeController@verifyStudent',
        'as' => 'verifystudent',
    ]);
    Route::get('/{section}/students', [
        'uses' => 'SectionController@students',
        'as' => 'section.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'SectionController@studentDetach',
        'as' => 'section.student-detach',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'company', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::get('/{company}/students', [
        'uses' => 'CompanyController@students',
        'as' => 'company.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'CompanyController@studentDetach',
        'as' => 'company.student-detach',
    ]);

});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
        'user_id',
        'name',
        'picture',
        'contact',
        'address',
        'email',
        'lng',
        'lat',
    ];

    public function students()
    {
        return $this->hasMany('App\Student');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use App\Role;
use App\Student;
use App\User;
use Illuminate\Http\Request;
use Image;

class CompanyController extends Controller
{
    public function index()
    {
        $companies = Company::all();
        return view('company.index', compact('companies'));
    }

    public function create()
    {
        return view('company.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        if ($request->has('picture')) {
            $picture = $request->file('picture');
            $filename = time() . '.' . $picture->getClientOriginalExtension();
            $data['picture'] = $filename;
            $background = Image::canvas(480, 360);
            $image = Image::make($picture)->resize(480, 360, function ($c) {
                $c->aspectRatio();
                $c->upsize();
            });
            $background->insert($image, 'center');
            $background->save(public_path('images/' . $filename));
        }
        $code = 'oims-' . mt_rand(5, 99999);
        $role_company = Role::where('name', 'Company')->first();
        $user = new User;
        $user_data = [
            'username' => $code,
            'password' => bcrypt($code),
        ];
        $user->fill($user_data)->save();
        $user->roles()->attach($role_company);
        $data['user_id'] = $user->id;
        $company = new Company;
        $company->fill($data)->save();
        return redirect()->route('company.index');
    }

    public function show($id)
    {
        return;
    }

    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit', compact('company', 'users'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        if ($request->has('picture')) {
            $picture = $request->file('picture');
            $filename = time() . '.' . $picture->getClientOriginalExtension();
            $data['picture'] = $filename;
            $background = Image::canvas(480, 360);
            $image = Image::make($picture)->resize(480, 360, function ($c) {
                $c->aspectRatio();
                $c->upsize();
            });
            $background->insert($image, 'center');
            $background->save(public_path('images/' . $filename));
        }
        $company = Company::find($id);
        $company->update($data);
        return redirect()->route('company.index');
    }

    public function destroy($id)
    {
        $company = Company::find($id);
        if (!empty($company->user)) {
            $company->user->delete();
        }
        $company->delete();
        return redirect()->back();
    }

    public function students($company_id)
    {
        $company = Company::find($company_id);
        $students = $company->students;
        return view('company.students', compact('company', 'students'));
    }

    public function studentDetach($student_id)
    {
        $student = Student::find($student_id);
        $student->company_id = null;
        $student->update();
        return redirect()->back();
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
              <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Create Company</span>
            </h3>
            </center>
            <hr>
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <form enctype="multipart/form-data" onsubmit="return confirm('Do you want to save this data?');" method="POST" action="{{ route('company.store') }}">
                        {{ csrf_field() }}
                        <div class="col-md-12">
                            <center>
                            <a class="thumbnail" href="#" data-target="#picture">
                                <img id="picture_view" src="{{ asset('images/dummy_company.png') }}" height="200" width="200" class="img-responsive" alt="picture">
                            </a>
                            </center>
                            <div class="form-group">
                                <center>
                                <button type="button" class="btn btn-info" id="file-upload">
                                <i class="fa fa-camera" aria-hidden="true"></i>
                                </button>
                            </center>
                                <input style="visibility: hidden;" type="file" name="picture" id="picture" class="hide" accept="image/*">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>
                            </div>
                            <div class="form-group">
                                <label for="name">Address</label>
                                <input autocomplete="off" class="form-control" id="autocomplete" name="address" value="{{ old('name') }}" type="text"></input>
                            </div>
                            <div class="form-group">
                                <label for="lat">Latitude</label>
                                <input type="text" readonly class="form-control" name="lat" id="lat">
                            </div>
                            <div class="form-group">
                                <label for="lng">Longitude</label>
                                <input type="text" readonly class="form-control" name="lng" id="lng">
                            </div>
                            <div class="form-group">
                                <label for="contact">Contact Number</label>
                                <input id="contact" type="text" class="form-control" name="contact" value="{{ old('contact') }}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email Address</label>
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyJ5_eYvROp8GJF74EOOFKf3v20dsIpj4&libraries=places&callback=initAutocomplete" async defer></script>
<script>
    $('#autocomplete').keypress(function(e){
        if ( e.which == 13 ) e.preventDefault();
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#picture_view').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#picture").change(function(){
        readURL(this);
    });
    $("#file-upload").on('click',function(){
       $("#picture").click();
    });

    var input = document.getElementById('autocomplete');
    var options = {
      types: ['establishment', 'geocode']
    };
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(input,options);
        autocomplete.addListener('place_changed', fillOrigin);
    }
    function fillOrigin() {
        var place = autocomplete.getPlace();
        var lat = place.geometry.location.lat();
        var lng = place.geometry.location.lng();
        $('#lng').val(lng);
        $('#lat').val(lat);
    }
</script>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
              <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Edit Company</span>
            </h3>
            </center>
            <hr>
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <form enctype="multipart/form-data" onsubmit="return confirm('Do you want to update this data?');" method="POST" action="{{ route('company.update', $company->id) }}">
                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}
                       <div class="col-md-12">
                            <center>
                            <a class="thumbnail" href="#" data-target="#picture">
                                <img id="picture_view" src="{{ asset('images/'. $company->picture) }}" height="200" width="200" class="img-responsive" alt="picture">
                            </a>
                            </center>
                            <div class="form-group">
                                <center>
                                <button type="button" class="btn btn-info" id="file-upload">
                                <i class="fa fa-camera" aria-hidden="true"></i>
                                </button>
                            </center>
                                <input style="visibility: hidden;" type="file" name="picture" id="picture" class="hide" accept="image/*">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input id="name" type="text" class="form-control" name="name" value="{{ $company->name }}" required autofocus>
                            </div>
                            <div class="form-group">
                                <label for="name">Address</label>
                                <input autocomplete="off" class="form-control" id="autocomplete" name="address" value="{{ $company->address }}" type="text"></input>
                            </div>
                            <div class="form-group">
                                <label for="lat">Latitude</label>
                                <input type="text" readonly class="form-control" value="{{ $company->lat }}" name="lat" id="lat">
                            </div>
                            <div class="form-group">
                                <label for="lng">Longitude</label>
                                <input type="text" readonly class="form-control" value="{{ $company->lng }}" name="lng" id="lng">
                            </div>
                            <div class="form-group">
                                <label for="contact">Contact Number</label>
                                <input id="contact" type="text" class="form-control" name="contact" value="{{ $company->contact }}">
                            </div>
                            <div class="form-group">
                                <label for="email">Email Address</label>
                                <input id="email" type="email" class="form-control" name="email" value="{{ $company->email }}">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success form-control">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
@endsection
@section('script')
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyJ5_eYvROp8GJF74EOOFKf3v20dsIpj4&libraries=places&callback=initAutocomplete" async defer></script>
<script>
    $('#autocomplete').keypress(function(e){
        if ( e.which == 13 ) e.preventDefault();
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#picture_view').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#picture").change(function(){
        readURL(this);
    });
    $("#file-upload").on('click',function(){
       $("#picture").click();
    });

    var input = document.getElementById('autocomplete');
    var options = {
      types: ['establishment', 'geocode']
    };
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(input,options);
        autocomplete.addListener('place_changed', fillOrigin);
    }
    function fillOrigin() {
        var place = autocomplete.getPlace();
        var lat = place.geometry.location.lat();
        var lng = place.geometry.location.lng();
        $('#lng').val(lng);
        $('#lat').val(lat);
    }
</script>
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="container-fluid p-4">
        <div class="col-md-12">
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Manage Company</span>
            </h3>
            </center>
            <hr>
            <br/>
            <div class="form-group">
                <a href="{{route('company.create')}}" class="btn btn-primary btn-lg">Create Company</a>
            </div>
            <hr>

            <div class="panel panel-default">
                <div class="panel-heading">Company</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Company</th>
                                    <th>Username</th>
                                    <th>Email Address</th>
                                    <th>Contact</th>
                                    <th>Number of Students</th>
                                    <th>Is Verified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($companies as $company)
                                <tr>
                                    <td>{{ $company->id }}</td>
                                    <td>{{ $company->name }}</td>
                                    <td>{{ $company->user->username }}</td>
                                    <td>{{ $company->email }}</td>
                                    <td>{{ $company->contact }}</td>
                                    <td>{{ sizeof($company->students) }}</td>
                                    <td>{{ $company->user->is_verified == 1 ? 'true' : 'false' }}</td>
                                    <td>
                                        <a href="{{route('company.students', $company->id)}}" class="btn btn-primary">Students</a>
                                        <a href="{{route('company.edit', $company->id)}}" class="btn btn-info">Edit</a>
                                        <button type="submit" form="company-delete-{{$company->id}}" class="btn btn-danger">Delete</button>
                                        <form onsubmit="return confirm('Do you want to delete this data?');" id="company-delete-{{$company->id}}" action="{{route('company.destroy', $company->id)}}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection

resources/views/company/students.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
          <div class="container-fluid p-4">
            <div class="col-md-12">
                <center>
                <h3 class="mb-0">
                    <span class="text-primary">Company Student List</span>
                </h3>
                </center>
                <hr>
            <div class="form-group">
                <a href="{{route('company.index')}}" class="btn btn-primary btn-lg">Company List</a>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Company {{$company->name}} student list</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>Student Number</th>
                                    <th>First Name</th>
                                    <th>Middle Name</th>
                                    <th>Last Name</th>
                                    <th>Username</th>
                                    <th>Section</th>
                                    <th>Email Address</th>
                                    <th>Contact</th>
                                    <th>Is Verified</th>
                                    <th>Remaining Time</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($students as $student)
                                @php
                                $total_hours = 0;
                                $total_minutes = 0;
                                @endphp
                                @foreach($student->user->timesheets as $timesheet)
                                @php
                                if(empty($timesheet->duration)) {
                                    $timesheet->duration = "0:0";
                                }
                                if($timesheet->is_checked) {
                                    $x = explode(':', $timesheet->duration);
                                    $total_hours = $total_hours + $x[0];
                                    $total_minutes = $total_minutes + $x[1];
                                }
                                @endphp
                                @endforeach
                                @php
                                $computed_time = intdiv($total_minutes, 60).':'. ($total_minutes % 60);
                                $exploded_time = explode(':', $computed_time);
                                $total_hours = $total_hours + (int)$exploded_time[0];
                                $rendered_total = sprintf("%d:%d", $total_hours, $exploded_time[1]);
                                @endphp
                                <tr>
                                    <td>{{ $student->student_number }}</td>
                                    <td>{{ $student->user->first_name }}</td>
                                    <td>{{ $student->user->middle_name }}</td>
                                    <td>{{ $student->user->last_name }}</td>
                                    <td>{{ $student->user->username }}</td>
                                    <td>{{ !empty($student->section) ? $student->section->name : '' }}</td>
                                    <td>{{ $student->user->email }}</td>
                                    <td>{{ $student->user->contact }}</td>
                                    <td>{{ $student->user->is_verified == 1 ? 'true' : 'false' }}</td>
                                    <td>{{ $student->remaining_time- (int)$rendered_total }}</td>
                                    <td>
                                        <button type="submit" form="company-detach-{{$student->id}}" class="btn btn-danger">Detach</button>
                                        <form onsubmit="return confirm('Do you want to delete this data?');" id="company-detach-{{$student->id}}" action="{{route('company.student-detach', $student->id)}}" method="POST">
                                            {{ method_field('PATCH') }}
                                            {{ csrf_field() }}
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection

resources/views/company/timesheet.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="container-fluid p-4">
            <div class="col-md-12">
                <center>
                <h3 class="mb-0">
                <span class="text-primary">Timesheet</span>
                </h3>
                </center>
                <hr>
                <br/>
            <div class="panel panel-default">
                <div class="panel-heading">Timesheets</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>Student</th>
                                    <th>Time In</th>
                                    <th>Time Out</th>
                                    <th>Task</th>
                                    <th>Duration</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($timesheets as $timesheet)
                                <tr>
                                    <td>{{ $timesheet->user->first_name }} {{ $timesheet->user->last_name }}</td>
                                    <td>{{ $timesheet->time_in }}</td>
                                    <td>{{ $timesheet->time_out }}</td>
                                    <td>{{ $timesheet->task }}</td>
                                    <td>{{ $timesheet->duration }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            </div>

        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection