routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'auth'], function () {

    Route::get('/dashboard', [
        'uses' => 'DashboardController@index',
        'as' => 'dashboard',
    ]);

    Route::get('/profile', [
        'uses' => 'ProfileController@index',
        'as' => 'profile',
    ]);

    Route::get('/profile-update-pass', [
        'uses' => 'ProfileController@pup',
        'as' => 'profile-update-pass',
    ]);

    Route::get('/profile-update', [
        'uses' => 'ProfileController@pu',
        'as' => 'profile-update',
    ]);

    Route::post('/profile-update-pass', [
        'uses' => 'ProfileController@pupx',
        'as' => 'profile-update-pass',
    ]);

    Route::post('/profile-update', [
        'uses' => 'ProfileController@pux',
        'as' => 'profile-update',
    ]);

    Route::group(['middleware' => ['role:Student']], function () {

        Route::get('/form-company', [
            'uses' => 'HomeController@company',
            'as' => 'requirements.company',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/timesheet-report', [
            'uses' => 'HomeController@reportTimesheet',
            'as' => 'report.timesheet',
        ]);

        Route::get('/form-information', [
            'uses' => 'HomeController@information',
            'as' => 'requirements.information',
            'middleware' => 'student.is-verified',
        ]);

        Route::get('/form-documents', [
            'uses' => 'HomeController@documents',
            'as' => 'requirements.documents',
            'middleware' => 'student.is-verified',
        ]);

        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);
        Route::patch('/update-student-requirements', [
            'uses' => 'HomeController@updateStudent',
            'as' => 'requirements.update-student',
            'middleware' => 'student.is-verified',
        ]);

    });

    Route::group(['middleware' => ['role:Company']], function () {

        Route::get('/company-students', [
            'uses' => 'DashboardController@companyStudents',
            'as' => 'company-students',
        ]);

        Route::get('/company-timesheets', [
            'uses' => 'DashboardController@timesheets',
            'as' => 'company-timesheets',
        ]);

        Route::get('/student-timesheet/{id}', [
            'uses' => 'DashboardController@studentTimesheet',
            'as' => 'student-timesheet',
        ]);

        Route::patch('/update-student-timesheet/{id}', [
            'uses' => 'DashboardController@updateStudentTimesheet',
            'as' => 'student-timesheet.update',
        ]);

    });

    Route::post('/logout', [
        'uses' => 'Auth\LoginController@logout',
        'as' => 'logout',
    ]);
});

Route::group(['middleware' => 'guest'], function () {

    Route::get('/', function () {
        return redirect()->route('login');
    });

    Route::get('/login', [
        'uses' => 'Auth\LoginController@loginForm',
        'as' => 'login',
    ]);

    Route::post('/login', [
        'uses' => 'Auth\LoginController@login',
        'as' => 'login',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Student', 'requirements']], function () {

    Route::resource('timesheet', 'TimesheetController');

    Route::post('/manual-add-time', [
        'uses' => 'TimesheetController@manualAddTime',
        'as' => 'manual.add.time',
    ]);

    Route::get('/ojt-form', [
        'uses' => 'ProfileController@ojtForm',
        'as' => 'ojt.form',
    ]);
});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::resource('section', 'SectionController');

    Route::resource('company', 'CompanyController');

    Route::resource('requirement', 'RequirementController');

    Route::resource('post', 'PostController');

    Route::resource('user', 'UserController');

    Route::resource('student', 'StudentController');

    Route::get('/profile-check/{id}', [
        'uses' => 'ProfileController@profilecheck',
        'as' => 'profile.check',
    ]);

});

Route::group(['middleware' => 'auth', 'middleware' => ['role:Admin']], function () {

    Route::resource('user', 'UserController');

    Route::post('/student/import', [
        'uses' => 'StudentController@importCsv',
        'as' => 'student.import',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'section', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::post('/revoke-req', [
        'uses' => 'HomeController@revokeReq',
        'as' => 'revoke.req',
    ]);

    Route::post('/verify-req', [
        'uses' => 'HomeController@verifyStudent',
        'as' => 'verifystudent',
    ]);
    Route::get('/{section}/students', [
        'uses' => 'SectionController@students',
        'as' => 'section.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'SectionController@studentDetach',
        'as' => 'section.student-detach',
    ]);

});

Route::group(['middleware' => 'auth', 'prefix' => 'company', 'middleware' => ['role:Admin|Practicum']], function () {

    Route::get('/{company}/students', [
        'uses' => 'CompanyController@students',
        'as' => 'company.students',
    ]);

    Route::patch('/student-detach/{student}', [
        'uses' => 'CompanyController@studentDetach',
        'as' => 'company.student-detach',
    ]);

});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable, EntrustUserTrait;

    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'username',
        'picture',
        'email',
        'contact',
        'reset',
        'password',
        'is_verified',
    ];

    protected $hidden = [
        'reset',
        'password',
        'remember_token',
    ];

    public function company()
    {
        return $this->hasMany('App\Company');
    }

    public function timesheets()
    {
        return $this->hasMany('App\Timesheet');
    }

    public function student()
    {
        return $this->hasOne('App\Student');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $all_users = User::all()->except(1);
        $users = [];
        foreach ($all_users as $key => $value) {
            if ($value->hasRole(['Admin', 'Practicum'])) {
                $users[] = $value;
            }
        }
        $roles = Role::all();
        return view('user.index', compact('users', 'roles'));
    }

    public function create()
    {
        $roles = Role::all();
        return view('user.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $user = new User;
        $code = 'oims-' . mt_rand(5, 99999);
        $request->request->add(['username' => $code]);
        $request->request->add(['password' => bcrypt($code)]);
        $user->fill($request->all())->save();
        $user->roles()->attach($request->role_id);
        return redirect()->route('user.index');
    }

    public function show($id)
    {
        return;
    }

    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::all();
        return view('user.edit', compact('user', 'roles'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->update($request->all());
        $user->roles()->detach();
        $user->roles()->attach($request->role_id);
        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        return;
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">Create User</div>
                <div class="panel-body">
                    <form onsubmit="return confirm('Do you want to save this data?');" method="POST" action="{{ route('user.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" class="form-control" name="first_name" value="{{ old('first_name') }}" required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="middle_name">Middle Name</label>
                            <input id="middle_name" type="text" class="form-control" name="middle_name" value="{{ old('middle_name') }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text" class="form-control" name="last_name" value="{{ old('last_name') }}" required>
                        </div>
                        <div class="form-group">
                            <label for="role_id">Role</label>
                            <select class="form-control" name="role_id" id="role_id" required>
                                <option {{ old('role_id') == null ? 'selected' : '' }} disabled>Select Role</option>
                                @foreach($roles->except([3,4]) as $role)
                                    <option {{ old('role_id') == $role->id ? 'selected' : '' }} value="{{$role->id}}">{{$role->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">Edit User</div>
                <div class="panel-body">
                    <form onsubmit="return confirm('Do you want to update this data?');" method="POST" action="{{ route('user.update', $user->id) }}">
                        {{ method_field('PATCH') }}
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input id="first_name" type="text" class="form-control" name="first_name" value="{{ $user->first_name }}" required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="middle_name">Middle Name</label>
                            <input id="middle_name" type="text" class="form-control" name="middle_name" value="{{ $user->middle_name }}">
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input id="last_name" type="text" class="form-control" name="last_name" value="{{ $user->last_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="role_id">Role</label>
                            <select class="form-control" name="role_id" id="role_id" required>
                                <option {{ $user->roles->first()->id == null ? 'selected' : '' }} disabled>Select Role</option>
                                @foreach($roles->except([3,4]) as $role)
                                    <option {{ $user->roles->first()->id == $role->id ? 'selected' : '' }} value="{{$role->id}}">{{$role->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success form-control">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('style')
<style>
    .text {
        display:inline-block;
    }
</style>
@endsection
@section('content')
<div class="container">
            <br/>
            <center>
            <h3 class="mb-0">
                <span class="text-primary">Manage User</span>
            </h3>
            </center>
            <hr>
            <br/>
            <br/>
    <div class="row">
        @foreach($roles as $role)
        <div class="col-sm-3">
            <div class="well">
                <i class="fa fa-user fa-4x fa-fw" aria-hidden="true"></i>
                <div class="text">
                    <h4>{{$role->name}}</h4>
                    <p>No : {{$role->users->count()}}</p>
                </div>
            </div>
        </div>
        @endforeach
    </div>
    <hr>
    <div class="row">
        <div class="container-fluid p-4">
        <div class="col-md-12">
            <div class="form-group">
                 <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createpost">
                    Create User
                    </button>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">User Management</div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="datatable">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Role</th>
                                    <th>Company</th>
                                    <th>Is Verified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{$user->first_name}} {{str_limit($user->middle_name, 1, '.')}} {{$user->last_name}}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>
                                        @foreach($user->roles as $role)
                                        {{$role->name}},
                                        @endforeach
                                    </td>
                                    <td>{{ !empty($user->company->first()) ? $user->company->first()->name : '' }}</td>
                                    <td>{{ $user->is_verified == 1 ? 'true' : 'false' }}</td>
                                    <td>
                                         <button type="button" class="btn btn-info" data-toggle="modal" data-target="#editpost-{{$user->id}}">
                                            Edit
                                            </button>
                                      {{--   <button type="submit" form="user-delete-{{$user->id}}" class="btn btn-danger">Delete</button>
                                        <form onsubmit="return confirm('Do you want to delete this data?');" id="user-delete-{{$user->id}}" action="{{route('user.destroy', $user->id)}}" method="POST">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                        </form> --}}
                                    </td>
                                </tr>
                                @include('user.includes._modalEdit')

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

@include('user.includes._modalAdd')
@endsection
@section('script')
<script>
    $(document).ready(function(){
        $('#datatable').DataTable();
    });
</script>
@endsection